# Generated by Django 5.1.5 on 2025-01-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyModel',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('NON IT', 'NON IT'), ('PHONES', 'PHONES')], max_length=200)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
